In [1]:
import pandas as pd
import numpy as np
import csv

from datetime import datetime
from datetime import timedelta

df1 = pd.read_excel(r"FILEPATH.xls", sheet_name='NAME')
df2 = pd.read_excel(r"FILEPATH.xls", sheet_name='NAME')
df9 = pd.read_excel(r"FILEPATH", sheet_name='NAME')

In [2]:
#How many rows?

len(df1.index)
len(df2.index)
len(df9.index)

4314

In [346]:
pd.set_option('display.max_rows', None)

In [3]:
for col in df1.columns:
    print(col)

In [3]:
count=df1['Subject ID'].value_counts()

In [4]:
count1=df1['Subject ID'].value_counts()

In [5]:
count1=df1['Subject ID'].value_counts().index.tolist()

count1.sort()

print(count1)

[50303.0, 50329.0, 50338.0, 50340.0, 50342.0, 50345.0, 50348.0, 50351.0, 50357.0, 50359.0, 50360.0, 50369.0, 50375.0, 50379.0, 50382.0, 50383.0, 50388.0, 50396.0, 50405.0, 50408.0, 50415.0, 50427.0, 50438.0, 50440.0, 50459.0, 50471.0, 50483.0, 50484.0, 50487.0, 50489.0, 50490.0, 50491.0, 50494.0, 50497.0, 50500.0, 50512.0, 50519.0, 50522.0, 50528.0, 50531.0, 50535.0, 50540.0, 50545.0, 50549.0, 50555.0, 50561.0, 50569.0, 50571.0, 50602.0, 50604.0, 50614.0, 50625.0, 50628.0, 50633.0, 50634.0, 50638.0, 50639.0, 50661.0, 50662.0, 50666.0, 50671.0, 50675.0, 50682.0, 50683.0, 50692.0, 50694.0, 50703.0, 50706.0, 50720.0, 50722.0, 50723.0, 50728.0, 50732.0, 50735.0, 50741.0, 50742.0, 50745.0, 50767.0, 50774.0, 50780.0, 50788.0]

In [6]:
count2=df2['Subject ID']. value_counts().index.tolist()
count2.sort()
print(count2)

[50334.0, 50404.0]

In [7]:
count9=df9['Subject ID']. value_counts().index.tolist()
count9.sort()
print (count9)

[50006.0, 50007.0, 50010.0, 50023.0, 50025.0, 50027.0, 50035.0, 50036.0, 50037.0, 50038.0, 50042.0, 50044.0, 50050.0, 50052.0, 50054.0, 50058.0, 50064.0, 50067.0, 50068.0, 50070.0, 50075.0, 50077.0, 50078.0, 50080.0, 50090.0, 50091.0, 50098.0, 50101.0, 50103.0, 50104.0, 50105.0, 50115.0, 50116.0, 50117.0, 50118.0, 50121.0, 50132.0, 50136.0, 50137.0, 50146.0, 50148.0, 50150.0, 50152.0, 50157.0, 50158.0, 50161.0, 50162.0, 50164.0, 50166.0, 50167.0, 50183.0, 50185.0, 50188.0, 50197.0, 50201.0, 50208.0, 50217.0, 50220.0, 50225.0, 50226.0, 50230.0, 50231.0, 50232.0, 50238.0, 50241.0, 50246.0, 50251.0, 50258.0, 50260.0, 50261.0, 50267.0, 50269.0, 50270.0, 50271.0, 50272.0, 50274.0, 50280.0, 50284.0, 50286.0, 50290.0, 50299.0, 50301.0, 50304.0, 50307.0, 50314.0, 50316.0, 50326.0, 50327.0]

In [8]:
#To append lists
for x in count2:
  count1.append(x)

print(count1)

[50303.0, 50329.0, 50338.0, 50340.0, 50342.0, 50345.0, 50348.0, 50351.0, 50357.0, 50359.0, 50360.0, 50369.0, 50375.0, 50379.0, 50382.0, 50383.0, 50388.0, 50396.0, 50405.0, 50408.0, 50415.0, 50427.0, 50438.0, 50440.0, 50459.0, 50471.0, 50483.0, 50484.0, 50487.0, 50489.0, 50490.0, 50491.0, 50494.0, 50497.0, 50500.0, 50512.0, 50519.0, 50522.0, 50528.0, 50531.0, 50535.0, 50540.0, 50545.0, 50549.0, 50555.0, 50561.0, 50569.0, 50571.0, 50602.0, 50604.0, 50614.0, 50625.0, 50628.0, 50633.0, 50634.0, 50638.0, 50639.0, 50661.0, 50662.0, 50666.0, 50671.0, 50675.0, 50682.0, 50683.0, 50692.0, 50694.0, 50703.0, 50706.0, 50720.0, 50722.0, 50723.0, 50728.0, 50732.0, 50735.0, 50741.0, 50742.0, 50745.0, 50767.0, 50774.0, 50780.0, 50788.0, 50334.0, 50404.0]

In [9]:
for x in count9:
  count1.append(x)

print(count1)

[50303.0, 50329.0, 50338.0, 50340.0, 50342.0, 50345.0, 50348.0, 50351.0, 50357.0, 50359.0, 50360.0, 50369.0, 50375.0, 50379.0, 50382.0, 50383.0, 50388.0, 50396.0, 50405.0, 50408.0, 50415.0, 50427.0, 50438.0, 50440.0, 50459.0, 50471.0, 50483.0, 50484.0, 50487.0, 50489.0, 50490.0, 50491.0, 50494.0, 50497.0, 50500.0, 50512.0, 50519.0, 50522.0, 50528.0, 50531.0, 50535.0, 50540.0, 50545.0, 50549.0, 50555.0, 50561.0, 50569.0, 50571.0, 50602.0, 50604.0, 50614.0, 50625.0, 50628.0, 50633.0, 50634.0, 50638.0, 50639.0, 50661.0, 50662.0, 50666.0, 50671.0, 50675.0, 50682.0, 50683.0, 50692.0, 50694.0, 50703.0, 50706.0, 50720.0, 50722.0, 50723.0, 50728.0, 50732.0, 50735.0, 50741.0, 50742.0, 50745.0, 50767.0, 50774.0, 50780.0, 50788.0, 50334.0, 50404.0, 50006.0, 50007.0, 50010.0, 50023.0, 50025.0, 50027.0, 50035.0, 50036.0, 50037.0, 50038.0, 50042.0, 50044.0, 50050.0, 50052.0, 50054.0, 50058.0, 50064.0, 50067.0, 50068.0, 50070.0, 50075.0, 50077.0, 50078.0, 50080.0, 50090.0, 50091.0, 50098.0, 50101.0, 50103.0, 50104.0, 50105.0, 50115.0, 50116.0, 50117.0, 50118.0, 50121.0, 50132.0, 50136.0, 50137.0, 50146.0, 50148.0, 50150.0, 50152.0, 50157.0, 50158.0, 50161.0, 50162.0, 50164.0, 50166.0, 50167.0, 50183.0, 50185.0, 50188.0, 50197.0, 50201.0, 50208.0, 50217.0, 50220.0, 50225.0, 50226.0, 50230.0, 50231.0, 50232.0, 50238.0, 50241.0, 50246.0, 50251.0, 50258.0, 50260.0, 50261.0, 50267.0, 50269.0, 50270.0, 50271.0, 50272.0, 50274.0, 50280.0, 50284.0, 50286.0, 50290.0, 50299.0, 50301.0, 50304.0, 50307.0, 50314.0, 50316.0, 50326.0, 50327.0]

In [10]:
ecapid = pd.DataFrame(count1,columns=['ID'])

print(ecapid)

          ID
0    50303.0
1    50329.0
2    50338.0
3    50340.0
4    50342.0
..       ...
166  50307.0
167  50314.0
168  50316.0
169  50326.0
170  50327.0

[171 rows x 1 columns]

In [11]:
ecapid.insert(1,"Medic",1)

ecapid

          ID  Medic
0    50303.0      1
1    50329.0      1
2    50338.0      1
3    50340.0      1
4    50342.0      1
..       ...    ...
166  50307.0      1
167  50314.0      1
168  50316.0      1
169  50326.0      1
170  50327.0      1

[171 rows x 2 columns]

In [12]:
print(ecapid.dtypes)

ID       float64
Medic      int64
dtype: object

In [13]:
#Convert id to integer
ecapid['ID'] = ecapid["ID"].astype(np.int64)

In [14]:
len(ecapid)

171

In [15]:
print(ecapid.dtypes)

ID       int64
Medic    int64
dtype: object

In [16]:
#Find duplicates
#No dups
df = pd.DataFrame(ecapid, columns = ['ID'])

duplicate = df[df.duplicated()]

print (duplicate)

Empty DataFrame
Columns: [ID]
Index: []

In [16]:
pd.DataFrame(ecapid).to_excel('ecapid.xlsx', index=False)
print('DataFrame is written to Excel File successfully.')

DataFrame is written to Excel File successfully.

In [17]:
#Stack all three datasets
concat = pd.concat([df2,df1,df9])

len(concat)

8973

In [18]:
print(concat.dtypes)

Package Index         float64
Study ID               object
Site ID                object
Subject ID            float64
Kit ID                 object
Package ID             object
Dose Regimen           object
Dose Index              int64
Dose Date              object
Dose Timestamp         object
Dose Timestamp UTC     object
Dose Group             object
Dose Label             object
Compliant              object
dtype: object

In [19]:
# Fill NaN values with the previous row values
concat['Subject ID'].fillna(method='ffill', inplace=True)
print(concat)

      Package Index Study ID       Site ID  Subject ID         Kit ID  \
0               1.0       --  REACH STROKE     50334.0  100014082-BR1
1               NaN      NaN           NaN     50334.0            NaN
2               NaN      NaN           NaN     50334.0            NaN
3               NaN      NaN           NaN     50334.0            NaN
4               NaN      NaN           NaN     50334.0            NaN
...             ...      ...           ...         ...            ...
4309            NaN      NaN           NaN     50327.0            NaN
4310            NaN      NaN           NaN     50327.0            NaN
4311            NaN      NaN           NaN     50327.0            NaN
4312            NaN      NaN           NaN     50327.0            NaN
4313            NaN      NaN           NaN     50327.0            NaN

         Package ID                Dose Regimen  Dose Index   Dose Date  \
0     100014082-BR1  eCap Twice a Day (default)           1  2018-01-14
1               NaN                         NaN           2         NaN
2               NaN                         NaN           3  2018-01-15
3               NaN                         NaN           4         NaN
4               NaN                         NaN           5  2018-01-16
...             ...                         ...         ...         ...
4309            NaN                         NaN          35  2018-06-23
4310            NaN                         NaN          36         NaN
4311            NaN                         NaN          37  2018-07-06
4312            NaN                         NaN          38         NaN
4313            NaN                         NaN          39  2018-07-14

                 Dose Timestamp         Dose Timestamp UTC Dose Group  \
0     2018-01-14T16:24:58-05:00  2018-01-14T21:24:58+00:00         --
1     2018-01-14T23:02:57-05:00  2018-01-15T04:02:57+00:00         --
2     2018-01-15T12:14:56-05:00  2018-01-15T17:14:56+00:00         --
3     2018-01-15T22:56:55-05:00  2018-01-16T03:56:55+00:00         --
4     2018-01-16T10:44:54-05:00  2018-01-16T15:44:54+00:00         --
...                         ...                        ...        ...
4309  2018-06-23T10:37:58-04:00  2018-06-23T14:37:58+00:00         --
4310  2018-06-23T17:27:58-04:00  2018-06-23T21:27:58+00:00         --
4311  2018-07-06T13:28:47-04:00  2018-07-06T17:28:47+00:00         --
4312  2018-07-06T14:10:47-04:00  2018-07-06T18:10:47+00:00         --
4313  2018-07-14T14:34:40-04:00  2018-07-14T18:34:40+00:00         --

       Dose Label Compliant
0     Twice a Day         0
1     Twice a Day         1
2     Twice a Day         1
3     Twice a Day         1
4     Twice a Day         1
...           ...       ...
4309            1        --
4310            1        --
4311            1        --
4312            1        --
4313            1        --

[8973 rows x 14 columns]

In [20]:
#Converted dose date to date format
concat["Dose Date"]= pd.to_datetime(concat["Dose Date"])

print(concat["Dose Date"])

0      2018-01-14
1             NaT
2      2018-01-15
3             NaT
4      2018-01-16
          ...
4309   2018-06-23
4310          NaT
4311   2018-07-06
4312          NaT
4313   2018-07-14
Name: Dose Date, Length: 8973, dtype: datetime64[ns]

In [21]:
len(concat)

8973

In [22]:
concat['Study ID'].value_counts()

--    171
Name: Study ID, dtype: int64

In [23]:
#Create new id var that is integer and descending sort
concat['ID'] = concat["Subject ID"].astype(np.int64)

#concat.sort_values('ID')

In [24]:
concat

,Package Index,Study ID,Site ID,Subject ID,Kit ID,Package ID,Dose Regimen,Dose Index,Dose Date,Dose Timestamp,Dose Timestamp UTC,Dose Group,Dose Label,Compliant,ID
0,1.0,--,REACH STROKE,50334.0,100014082-BR1,100014082-BR1,eCap Twice a Day (default),1,2018-01-14,2018-01-14T16:24:58-05:00,2018-01-14T21:24:58+00:00,--,Twice a Day,0,50334
1,NaN,NaN,NaN,50334.0,NaN,NaN,NaN,2,NaT,2018-01-14T23:02:57-05:00,2018-01-15T04:02:57+00:00,--,Twice a Day,1,50334
2,NaN,NaN,NaN,50334.0,NaN,NaN,NaN,3,2018-01-15,2018-01-15T12:14:56-05:00,2018-01-15T17:14:56+00:00,--,Twice a Day,1,50334
3,NaN,NaN,NaN,50334.0,NaN,NaN,NaN,4,NaT,2018-01-15T22:56:55-05:00,2018-01-16T03:56:55+00:00,--,Twice a Day,1,50334
4,NaN,NaN,NaN,50334.0,NaN,NaN,NaN,5,2018-01-16,2018-01-16T10:44:54-05:00,2018-01-16T15:44:54+00:00,--,Twice a Day,1,50334
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4309,NaN,NaN,NaN,50327.0,NaN,NaN,NaN,35,2018-06-23,2018-06-23T10:37:58-04:00,2018-06-23T14:37:58+00:00,--,1,--,50327
4310,NaN,NaN,NaN,50327.0,NaN,NaN,NaN,36,NaT,2018-06-23T17:27:58-04:00,2018-06-23T21:27:58+00:00,--,1,--,50327
4311,NaN,NaN,NaN,50327.0,NaN,NaN,NaN,37,2018-07-06,2018-07-06T13:28:47-04:00,2018-07-06T17:28:47+00:00,--,1,--,50327
4312,NaN,NaN,NaN,50327.0,NaN,NaN,NaN,38,NaT,2018-07-06T14:10:47-04:00,2018-07-06T18:10:47+00:00,--,1,--,50327
4313,NaN,NaN,NaN,50327.0,NaN,NaN,NaN,39,2018-07-14,2018-07-14T14:34:40-04:00,2018-07-14T18:34:40+00:00,--,1,--,50327

In [482]:
pd.DataFrame(concat).to_csv('concat.csv', index=False)
print('DataFrame is written to csv File successfully.')

In [389]:
print(concat.dtypes)

In [366]:
len(concat)

In [24]:
concat['Study ID'].value_counts()

--    171
Name: Study ID, dtype: int64

In [25]:
concat['ID'].value_counts()

50528    211
50148    179
50197    175
50404    166
50638    160
        ...
50531      1
50078      1
50067      1
50068      1
50360      1
Name: ID, Length: 171, dtype: int64

In [26]:
concat['Dose Label'].value_counts()

Once a Day     4371
1              4314
Twice a Day     288
Name: Dose Label, dtype: int64

In [27]:
#How to drop columns
concat1 = concat.drop(["Package Index","Package ID", "Study ID","Subject ID", "Site ID","Kit ID","Dose Regimen", "Dose Group", "Compliant"],axis=1)

In [28]:
#Create new vars
#Keep certain number of stings in obj
concat1['OpenDate_DHM'] = concat1["Dose Timestamp"].str[:16]

print (concat1['OpenDate_DHM'])

0       2018-01-14T16:24
1       2018-01-14T23:02
2       2018-01-15T12:14
3       2018-01-15T22:56
4       2018-01-16T10:44
              ...
4309    2018-06-23T10:37
4310    2018-06-23T17:27
4311    2018-07-06T13:28
4312    2018-07-06T14:10
4313    2018-07-14T14:34
Name: OpenDate_DHM, Length: 8973, dtype: object

In [29]:
str(concat1['OpenDate_DHM'])
print (concat1['OpenDate_DHM'])

0       2018-01-14T16:24
1       2018-01-14T23:02
2       2018-01-15T12:14
3       2018-01-15T22:56
4       2018-01-16T10:44
              ...
4309    2018-06-23T10:37
4310    2018-06-23T17:27
4311    2018-07-06T13:28
4312    2018-07-06T14:10
4313    2018-07-14T14:34
Name: OpenDate_DHM, Length: 8973, dtype: object

In [30]:
print(concat1.dtypes)

Dose Index                     int64
Dose Date             datetime64[ns]
Dose Timestamp                object
Dose Timestamp UTC            object
Dose Label                    object
ID                             int64
OpenDate_DHM                  object
dtype: object

In [31]:
concat['Dose Label'].value_counts()

Once a Day     4371
1              4314
Twice a Day     288
Name: Dose Label, dtype: int64

In [33]:
concat['Dose Index'].value_counts()

1      171
3      155
2      155
4      150
6      148
      ...
183      1
182      1
181      1
180      1
211      1
Name: Dose Index, Length: 211, dtype: int64

In [32]:
concat1 = concat.reindex(columns=['ID','Dose Label','Dose Date','Dose Index'])

In [33]:
print(concat1.dtypes)

ID                     int64
Dose Label            object
Dose Date     datetime64[ns]
Dose Index             int64
dtype: object

In [34]:
concat1['Day num'] = np.where(concat1['Dose Index'] == 1, 1, 0 )

print(concat1)

         ID   Dose Label  Dose Date  Dose Index  Day num
0     50334  Twice a Day 2018-01-14           1        1
1     50334  Twice a Day        NaT           2        0
2     50334  Twice a Day 2018-01-15           3        0
3     50334  Twice a Day        NaT           4        0
4     50334  Twice a Day 2018-01-16           5        0
...     ...          ...        ...         ...      ...
4309  50327            1 2018-06-23          35        0
4310  50327            1        NaT          36        0
4311  50327            1 2018-07-06          37        0
4312  50327            1        NaT          38        0
4313  50327            1 2018-07-14          39        0

[8973 rows x 5 columns]

In [35]:
print(concat1.dtypes)
#Day num is created in this full dataset with 1 or 0.

ID                     int64
Dose Label            object
Dose Date     datetime64[ns]
Dose Index             int64
Day num                int32
dtype: object

In [36]:
concat1['ID'].value_counts()

50528    211
50148    179
50197    175
50404    166
50638    160
        ...
50531      1
50078      1
50067      1
50068      1
50360      1
Name: ID, Length: 171, dtype: int64

In [ ]:
#Create separate datasets and then locate last obs

In [37]:
#Locate only the vars day num = 1
day1 = concat1.loc[concat1['Day num']== 1]

day1

         ID   Dose Label  Dose Date  Dose Index  Day num
0     50334  Twice a Day 2018-01-14           1        1
122   50404  Twice a Day 2018-06-21           1        1
0     50303   Once a Day 2018-02-12           1        1
31    50329   Once a Day 2018-01-13           1        1
32    50338   Once a Day 2018-02-07           1        1
...     ...          ...        ...         ...      ...
3972  50307            1 2017-12-05           1        1
3998  50314            1 2017-12-08           1        1
4104  50316            1 2017-12-07           1        1
4192  50326            1 2018-01-11           1        1
4275  50327            1 2018-01-04           1        1

[171 rows x 5 columns]

In [38]:
len(day1)

171

In [39]:
print(day1.dtypes)

ID                     int64
Dose Label            object
Dose Date     datetime64[ns]
Dose Index             int64
Day num                int32
dtype: object

In [41]:
#Create a subset of columns
day2 = day1.loc[:,['ID','Day num', 'Dose Label','Dose Date']]

day2

         ID  Day num   Dose Label  Dose Date
0     50334        1  Twice a Day 2018-01-14
122   50404        1  Twice a Day 2018-06-21
0     50303        1   Once a Day 2018-02-12
31    50329        1   Once a Day 2018-01-13
32    50338        1   Once a Day 2018-02-07
...     ...      ...          ...        ...
3972  50307        1            1 2017-12-05
3998  50314        1            1 2017-12-08
4104  50316        1            1 2017-12-07
4192  50326        1            1 2018-01-11
4275  50327        1            1 2018-01-04

[171 rows x 4 columns]

In [42]:
s = day2['Dose Date']

day2['Last Date_50'] = s + timedelta(days=50)


print(day2['Last Date_50'])

0      2018-03-05
122    2018-08-10
0      2018-04-03
31     2018-03-04
32     2018-03-29
          ...
3972   2018-01-24
3998   2018-01-27
4104   2018-01-26
4192   2018-03-02
4275   2018-02-23
Name: Last Date_50, Length: 171, dtype: datetime64[ns]

In [43]:
day2.head()

        ID  Day num   Dose Label  Dose Date Last Date_50
0    50334        1  Twice a Day 2018-01-14   2018-03-05
122  50404        1  Twice a Day 2018-06-21   2018-08-10
0    50303        1   Once a Day 2018-02-12   2018-04-03
31   50329        1   Once a Day 2018-01-13   2018-03-04
32   50338        1   Once a Day 2018-02-07   2018-03-29

In [42]:
print(day2.dtypes)

ID                     int64
Day num                int32
Dose Label            object
Dose Date     datetime64[ns]
End Date      datetime64[ns]
dtype: object

In [45]:
day2['ID_str'] = day2['ID'].astype("string")

day2

         ID  Day num   Dose Label  Dose Date Last Date_50 ID_str
0     50334        1  Twice a Day 2018-01-14   2018-03-05  50334
122   50404        1  Twice a Day 2018-06-21   2018-08-10  50404
0     50303        1   Once a Day 2018-02-12   2018-04-03  50303
31    50329        1   Once a Day 2018-01-13   2018-03-04  50329
32    50338        1   Once a Day 2018-02-07   2018-03-29  50338
...     ...      ...          ...        ...          ...    ...
3972  50307        1            1 2017-12-05   2018-01-24  50307
3998  50314        1            1 2017-12-08   2018-01-27  50314
4104  50316        1            1 2017-12-07   2018-01-26  50316
4192  50326        1            1 2018-01-11   2018-03-02  50326
4275  50327        1            1 2018-01-04   2018-02-23  50327

[171 rows x 6 columns]

In [46]:
print(day2.dtypes)

ID                       int64
Day num                  int32
Dose Label              object
Dose Date       datetime64[ns]
Last Date_50    datetime64[ns]
ID_str                  string
dtype: object

In [47]:
list_A = day2['ID'].tolist()

In [48]:
#CREATE INDIVIDUAL DATASETS
for i in list_A:
    df = concat1.loc[concat1['ID']== i]

    #df.to_csv(f'ID_{i}.csv', encoding="utf-8", index=False)
    df.to_csv(f'FILEPATH\\ID_{i}.csv', index=False)

In [49]:
day2

         ID  Day num   Dose Label  Dose Date Last Date_50 ID_str
0     50334        1  Twice a Day 2018-01-14   2018-03-05  50334
122   50404        1  Twice a Day 2018-06-21   2018-08-10  50404
0     50303        1   Once a Day 2018-02-12   2018-04-03  50303
31    50329        1   Once a Day 2018-01-13   2018-03-04  50329
32    50338        1   Once a Day 2018-02-07   2018-03-29  50338
...     ...      ...          ...        ...          ...    ...
3972  50307        1            1 2017-12-05   2018-01-24  50307
3998  50314        1            1 2017-12-08   2018-01-27  50314
4104  50316        1            1 2017-12-07   2018-01-26  50316
4192  50326        1            1 2018-01-11   2018-03-02  50326
4275  50327        1            1 2018-01-04   2018-02-23  50327

[171 rows x 6 columns]

In [50]:
#Another list 
list_str = day2['ID_str'].tolist()

list_str

['50334',
 '50404',
 '50303',
 '50329',
 '50338',
 '50340',
 '50342',
 '50345',
 '50348',
 '50351',
 '50357',
 '50359',
 '50360',
 '50369',
 '50375',
 '50379',
 '50382',
 '50383',
 '50388',
 '50396',
 '50405',
 '50408',
 '50415',
 '50427',
 '50438',
 '50440',
 '50459',
 '50471',
 '50483',
 '50484',
 '50487',
 '50489',
 '50490',
 '50491',
 '50494',
 '50497',
 '50500',
 '50512',
 '50519',
 '50522',
 '50528',
 '50531',
 '50535',
 '50540',
 '50545',
 '50549',
 '50555',
 '50561',
 '50569',
 '50571',
 '50602',
 '50604',
 '50614',
 '50625',
 '50628',
 '50633',
 '50634',
 '50638',
 '50639',
 '50661',
 '50662',
 '50666',
 '50671',
 '50675',
 '50682',
 '50683',
 '50692',
 '50694',
 '50703',
 '50706',
 '50720',
 '50722',
 '50723',
 '50728',
 '50732',
 '50735',
 '50741',
 '50742',
 '50745',
 '50767',
 '50774',
 '50780',
 '50788',
 '50006',
 '50007',
 '50010',
 '50023',
 '50025',
 '50027',
 '50035',
 '50036',
 '50037',
 '50038',
 '50042',
 '50044',
 '50050',
 '50052',
 '50054',
 '50058',
 '50064',
 '50067',
 '50068',
 '50070',
 '50075',
 '50077',
 '50078',
 '50080',
 '50090',
 '50091',
 '50098',
 '50101',
 '50103',
 '50104',
 '50105',
 '50115',
 '50116',
 '50117',
 '50118',
 '50121',
 '50132',
 '50136',
 '50137',
 '50146',
 '50148',
 '50150',
 '50152',
 '50157',
 '50158',
 '50161',
 '50162',
 '50164',
 '50166',
 '50167',
 '50183',
 '50185',
 '50188',
 '50197',
 '50201',
 '50208',
 '50217',
 '50220',
 '50225',
 '50226',
 '50230',
 '50231',
 '50232',
 '50238',
 '50241',
 '50246',
 '50251',
 '50258',
 '50260',
 '50261',
 '50267',
 '50269',
 '50270',
 '50271',
 '50272',
 '50274',
 '50280',
 '50284',
 '50286',
 '50290',
 '50299',
 '50301',
 '50304',
 '50307',
 '50314',
 '50316',
 '50326',
 '50327']

In [ ]:
#ADD end dates to new dataset 'start_end_dates'

In [54]:
import glob

print('all csv files in data directory:', glob.glob('FILEPATH\\ID_*.csv'))

all csv files in data directory: ['C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50006.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50007.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50010.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50023.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50025.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50027.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50035.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50036.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50037.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50038.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50042.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50044.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50050.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50052.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50054.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50058.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50064.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50067.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50068.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50070.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50075.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50077.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50078.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50080.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50090.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50091.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50098.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50101.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50103.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50104.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50105.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50115.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50116.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50117.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50118.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50121.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50132.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50136.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50137.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50146.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50148.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50150.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50152.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50157.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50158.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50161.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50162.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50164.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50166.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50167.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50183.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50185.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50188.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50197.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50201.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50208.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50217.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50220.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50225.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50226.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50230.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50231.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50232.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50238.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50241.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50246.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50251.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50258.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50260.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50261.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50267.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50269.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50270.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50271.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50272.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50274.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50280.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50284.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50286.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50290.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50299.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50301.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50303.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50304.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50307.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50314.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50316.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50326.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50327.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50329.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50334.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50338.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50340.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50342.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50345.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50348.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50351.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50357.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50359.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50360.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50369.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50375.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50379.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50382.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50383.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50388.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50396.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50404.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50405.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50408.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50415.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50427.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50438.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50440.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50459.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50471.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50483.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50484.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50487.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50489.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50490.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50491.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50494.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50497.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50500.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50512.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50519.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50522.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50528.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50531.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50535.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50540.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50545.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50549.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50555.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50561.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50569.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50571.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50602.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50604.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50614.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50625.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50628.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50633.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50634.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50638.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50639.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50661.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50662.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50666.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50671.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50675.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50682.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50683.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50692.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50694.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50703.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50706.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50720.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50722.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50723.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50728.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50732.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50735.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50741.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.edu\\All Documents\\Stroke\\Stroke eCAP\\Individual files\\ID_50742.csv', 'C:\\Users\\sjl2172\\OneDrive - cumc.columbia.

In [55]:
for filename in glob.glob('ID_*.csv'):
    data = pd.read_csv(filename)
    print(data.iloc[-1:])

       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
94  50006           1  2017-02-19  2017-02-19T11:55:07-05:00          95

    Day num
94        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
94  50007           1  2017-02-19  2017-02-19T09:28:37-05:00          95

    Day num
94        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
31  50010           1  2017-02-27  2017-02-27T09:38:48-05:00          32

    Day num
31        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
17  50023           1  2017-02-20  2017-02-20T14:48:17-05:00          18

    Day num
17        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
47  50025           1  2017-04-12  2017-04-12T12:49:11-04:00          48

    Day num
47        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
47  50027           1  2017-02-14  2017-02-14T06:54:23-05:00          48

    Day num
47        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50035           1  2017-04-10  2017-04-10T11:49:07-04:00          31

    Day num
30        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
28  50036           1  2018-03-10  2018-03-10T12:52:18-05:00          29

    Day num
28        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
27  50037           1  2017-07-17  2017-07-17T14:54:04-04:00          28

    Day num
27        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
46  50038           1  2017-04-09  2017-04-09T11:05:36-04:00          47

    Day num
46        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
57  50042           1  2017-04-15  2017-04-15T20:54:19-04:00          58

    Day num
57        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50044           1  2017-04-11  2017-04-11T13:02:03-04:00          31

    Day num
30        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
110  50050           1  2017-04-30  2017-04-30T07:43:10-04:00         111

     Day num
110        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50052           1  2017-04-10  2017-04-10T15:27:13-04:00           1

   Day num
0        1
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
2  50054           1  2017-01-26  2017-01-26T15:39:43-05:00           3

   Day num
2        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
49  50058           1  2017-04-13  2017-04-13T13:47:59-04:00          50

    Day num
49        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
55  50064           1  2017-04-09  2017-04-09T11:28:02-04:00          56

    Day num
55        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50067           1  2017-05-08  2017-05-08T12:57:46-04:00           1

   Day num
0        1
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50068           1  2017-03-14  2017-03-14T14:14:04-04:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
47  50070           1  2017-05-11  2017-05-11T14:47:15-04:00          48

    Day num
47        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
53  50075           1  2017-04-26  2017-04-26T19:33:58-04:00          54

    Day num
53        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50077           1  2018-03-19  2018-03-19T17:55:28-04:00           1

   Day num
0        1
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50078           1  2017-04-04  2017-04-04T12:05:27-04:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
74  50080           1  2017-04-10  2017-04-10T19:59:46-04:00          75

    Day num
74        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
95  50090           1  2017-05-20  2017-05-20T01:50:37-04:00          96

    Day num
95        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
29  50091           1  2017-04-09  2017-04-09T21:10:29-04:00          30

    Day num
29        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
31  50098           1  2017-03-30  2017-03-30T18:07:07-04:00          32

    Day num
31        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
28  50101           1  2017-04-02  2017-04-02T18:08:34-04:00          29

    Day num
28        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
58  50103           1  2017-05-02  2017-05-02T18:24:14-04:00          59

    Day num
58        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
36  50104           1  2017-04-08  2017-04-08T22:32:08-04:00          37

    Day num
36        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
49  50105           1  2017-05-13  2017-05-13T21:15:56-04:00          50

    Day num
49        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50115           1  2017-06-27  2017-06-27T13:54:25-04:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
35  50116           1  2017-07-04  2017-07-04T20:20:02-04:00          36

    Day num
35        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50117           1  2017-02-28  2017-02-28T13:14:43-05:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
34  50118           1  2017-07-16  2017-07-16T08:38:40-04:00          35

    Day num
34        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
13  50121           1  2017-05-29  2017-05-29T14:13:26-04:00          14

    Day num
13        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
25  50132           1  2017-07-20  2017-07-20T16:49:56-04:00          26

    Day num
25        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
53  50136           1  2017-05-30  2017-05-30T04:24:40-04:00          54

    Day num
53        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
28  50137           1  2017-05-31  2017-05-31T18:21:13-04:00          29

    Day num
28        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
64  50146           1  2017-06-30  2017-06-30T22:17:20-04:00          65

    Day num
64        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
178  50148           1  2018-02-18  2018-02-18T13:03:32-05:00         179

     Day num
178        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
53  50150           1  2017-07-01  2017-07-01T09:13:52-04:00          54

    Day num
53        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
96  50152           1  2017-08-10  2017-08-10T23:19:13-04:00          97

    Day num
96        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
64  50157           1  2017-08-08  2017-08-08T12:08:26-04:00          65

    Day num
64        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50158           1  2017-08-04  2017-08-04T11:34:42-04:00          31

    Day num
30        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
83  50161           1  2017-07-18  2017-07-18T06:33:41-04:00          84

    Day num
83        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
15  50162           1  2017-08-01  2017-08-01T08:01:25-04:00          16

    Day num
15        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
32  50164           1  2017-07-23  2017-07-23T07:11:04-04:00          33

    Day num
32        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
6  50166           1  2017-08-14  2017-08-14T07:42:28-04:00           7

   Day num
6        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50167           1  2017-07-22  2017-07-22T07:54:28-04:00          31

    Day num
30        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
69  50183           1  2017-09-13  2017-09-13T16:57:47-04:00          70

    Day num
69        0

       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
22  50185           1  2017-09-28  2017-09-28T00:21:38-04:00          23

    Day num
22        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50188           1  2017-06-21  2017-06-21T21:21:20-04:00           1

   Day num
0        1
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
174  50197           1  2017-10-23  2017-10-23T08:22:24-04:00         175

     Day num
174        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
41  50201           1  2017-09-22  2017-09-22T10:11:39-04:00          42

    Day num
41        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
125  50208           1  2017-10-19  2017-10-19T16:53:00-04:00         126

     Day num
125        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
56  50217           1  2017-09-14  2017-09-14T21:26:23-04:00          57

    Day num
56        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
117  50220           1  2017-09-21  2017-09-21T01:02:46-04:00         118

     Day num
117        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
50  50225           1  2017-10-18  2017-10-18T14:51:49-04:00          51

    Day num
50        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
9  50226           1  2018-02-16  2018-02-16T23:50:52-05:00          10

   Day num
9        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50230           1  2018-02-22  2018-02-22T14:33:44-05:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
68  50231           1  2017-10-18  2017-10-18T17:16:46-04:00          69

    Day num
68        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50232           1  2017-10-27  2017-10-27T13:00:04-04:00          31

    Day num
30        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
56  50238           1  2017-10-18  2017-10-18T20:46:50-04:00          57

    Day num
56        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
60  50241           1  2017-10-27  2017-10-27T12:02:06-04:00          61

    Day num
60        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
38  50246           1  2017-10-18  2017-10-18T12:35:47-04:00          39

    Day num
38        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
85  50251           1  2017-11-15  2017-11-15T09:28:29-05:00          86

    Day num
85        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
50  50258           1  2017-11-16  2017-11-16T01:10:55-05:00          51

    Day num
50        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
51  50260           1  2017-11-13  2017-11-13T19:05:46-05:00          52

    Day num
51        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
49  50261           1  2017-11-28  2017-11-28T08:32:32-05:00          50

    Day num
49        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
37  50267           1  2017-12-29  2017-12-29T13:53:53-05:00          38

    Day num
37        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
54  50269           1  2017-12-08  2017-12-08T22:50:58-05:00          55

    Day num
54        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
59  50270           1  2017-11-18  2017-11-18T21:43:32-05:00          60

    Day num
59        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
42  50271           1  2017-11-19  2017-11-19T12:01:42-05:00          43

    Day num
42        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
34  50272           1  2017-12-02  2017-12-02T01:37:47-05:00          35

    Day num
34        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
84  50274           1  2018-01-09  2018-01-09T06:23:11-05:00          85

    Day num
84        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
61  50280           1  2018-01-09  2018-01-09T10:53:54-05:00          62

    Day num
61        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
19  50284           1  2018-03-12  2018-03-12T14:03:09-04:00          20

    Day num
19        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
57  50286           1  2017-12-21  2017-12-21T11:10:40-05:00          58

    Day num
57        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
61  50290           1  2018-01-17  2018-01-17T17:48:42-05:00          62

    Day num
61        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
18  50299           1  2017-12-13  2017-12-13T13:51:49-05:00          19

    Day num
18        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
53  50301           1  2018-01-08  2018-01-08T22:14:42-05:00          54

    Day num
53        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50303  Once a Day  2018-03-15  2018-03-15T08:54:16-04:00          31

    Day num
30        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
57  50304           1  2018-04-03  2018-04-03T06:44:39-04:00          58

    Day num
57        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
25  50307           1  2018-01-28  2018-01-28T14:47:09-05:00          26

    Day num
25        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
105  50314           1  2018-04-19  2018-04-19T15:52:40-04:00         106

     Day num
105        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
87  50316           1  2018-03-13  2018-03-13T12:58:37-04:00          88

    Day num
87        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
82  50326           1  2018-04-23  2018-04-23T14:05:58-04:00          83

    Day num
82        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
38  50327           1  2018-07-14  2018-07-14T14:34:40-04:00          39

    Day num
38        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50329  Once a Day  2018-01-13  2018-01-13T00:23:31-05:00           1

   Day num
0        1
        ID   Dose Label   Dose Date             Dose Timestamp  Dose Index  \
121  50334  Twice a Day  2018-04-07  2018-04-07T21:59:47-04:00         122

     Day num
121        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
20  50338  Once a Day  2018-04-23  2018-04-23T21:40:43-04:00          21

    Day num
20        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
31  50340  Once a Day  2018-03-21  2018-03-21T08:50:45-04:00          32

    Day num
31        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
54  50342  Once a Day  2018-04-22  2018-04-22T16:11:25-04:00          55

    Day num
54        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
154  50345  Once a Day  2018-08-15  2018-08-15T07:11:45-04:00         155

     Day num
154        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50348  Once a Day  2018-07-16  2018-07-16T15:07:57-04:00          31

    Day num
30        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
72  50351  Once a Day  2018-04-29  2018-04-29T22:12:58-04:00          73

    Day num
72        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
65  50357  Once a Day  2018-05-12  2018-05-12T07:59:26-04:00          66

    Day num
65        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
11  50359  Once a Day  2018-06-01  2018-06-01T13:12:32-04:00          12

    Day num
11        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50360  Once a Day  2018-03-16  2018-03-16T13:23:25-04:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
88  50369  Once a Day  2018-06-10  2018-06-10T20:17:06-04:00          89

    Day num
88        0

       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
64  50375  Once a Day  2018-06-11  2018-06-11T19:55:32-04:00          65

    Day num
64        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50379  Once a Day  2018-04-19  2018-04-19T22:13:25-04:00          31

    Day num
30        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
84  50382  Once a Day  2018-07-07  2018-07-07T08:39:31-04:00          85

    Day num
84        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
8  50383  Once a Day  2018-07-10  2018-07-10T01:53:04-04:00           9

   Day num
8        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
87  50388  Once a Day  2018-07-07  2018-07-07T10:18:53-04:00          88

    Day num
87        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
70  50396  Once a Day  2018-09-04  2018-09-04T16:45:15-04:00          71

    Day num
70        0
        ID   Dose Label   Dose Date             Dose Timestamp  Dose Index  \
165  50404  Twice a Day  2018-09-12  2018-09-12T23:43:39-04:00         166

     Day num
165        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50405  Once a Day  2018-05-23  2018-05-23T06:53:22-04:00          31

    Day num
30        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
3  50408  Once a Day  2018-09-21  2018-09-21T10:10:05-04:00           4

   Day num
3        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
51  50415  Once a Day  2018-08-10  2018-08-10T07:56:23-04:00          52

    Day num
51        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
38  50427  Once a Day  2018-11-06  2018-11-06T10:31:12-05:00          39

    Day num
38        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
43  50438  Once a Day  2018-09-25  2018-09-25T21:18:24-04:00          44

    Day num
43        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
50  50440  Once a Day  2018-11-15  2018-11-15T22:48:55-05:00          51

    Day num
50        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
116  50459  Once a Day  2018-12-19  2018-12-19T22:30:06-05:00         117

     Day num
116        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
100  50471  Once a Day  2018-11-22  2018-11-22T10:20:24-05:00         101

     Day num
100        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
144  50483  Once a Day  2019-01-02  2019-01-02T12:17:07-05:00         145

     Day num
144        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50484  Once a Day  2019-02-11  2019-02-11T10:32:55-05:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
17  50487  Once a Day  2018-10-10  2018-10-10T11:03:37-04:00          18

    Day num
17        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
102  50489  Once a Day  2018-11-20  2018-11-20T07:24:16-05:00         103

     Day num
102        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
57  50490  Once a Day  2018-12-24  2018-12-24T22:59:16-05:00          58

    Day num
57        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
2  50491  Once a Day  2018-09-21  2018-09-21T09:04:58-04:00           3

   Day num
2        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
85  50494  Once a Day  2019-01-28  2019-01-28T20:19:30-05:00          86

    Day num
85        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
2  50497  Once a Day  2018-10-20  2018-10-20T12:44:32-04:00           3

   Day num
2        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
85  50500  Once a Day  2018-12-14  2018-12-14T07:14:07-05:00          86

    Day num
85        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
33  50512  Once a Day  2018-11-11  2018-11-11T16:53:49-05:00          34

    Day num
33        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
35  50519  Once a Day  2019-01-14  2019-01-14T14:05:32-05:00          36

    Day num
35        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
29  50522  Once a Day  2018-11-01  2018-11-01T17:12:23-04:00          30

    Day num
29        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
210  50528  Once a Day  2019-03-09  2019-03-09T22:32:16-05:00         211

     Day num
210        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50531  Once a Day  2018-10-09  2018-10-09T16:59:56-04:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
70  50535  Once a Day  2019-03-02  2019-03-02T10:52:34-05:00          71

    Day num
70        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
76  50540  Once a Day  2019-02-14  2019-02-14T08:44:35-05:00          77

    Day num
76        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
153  50545  Once a Day  2019-03-01  2019-03-01T23:44:59-05:00         154

     Day num
153        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
117  50549  Once a Day  2019-03-04  2019-03-04T17:29:45-05:00         118

     Day num
117        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
58  50555  Once a Day  2019-03-14  2019-03-14T13:04:01-04:00          59

    Day num
58        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
3  50561  Once a Day  2019-03-18  2019-03-18T10:39:47-04:00           4

   Day num
3        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50569  Once a Day  2018-11-28  2018-11-28T06:12:06-05:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
19  50571  Once a Day  2019-01-29  2019-01-29T15:16:21-05:00          20

    Day num
19        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
47  50602  Once a Day  2019-03-23  2019-03-23T13:50:15-04:00          48

    Day num
47        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50604  Once a Day  2019-01-08  2019-01-08T16:53:47-05:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
91  50614  Once a Day  2019-04-29  2019-04-29T08:27:16-04:00          92

    Day num
91        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
29  50625  Once a Day  2019-02-09  2019-02-09T09:00:48-05:00          30

    Day num
29        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
29  50628  Once a Day  2019-03-15  2019-03-15T10:16:06-04:00          30

    Day num
29        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
32  50633  Once a Day  2019-04-05  2019-04-05T17:41:12-04:00          33

    Day num
32        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
85  50634  Once a Day  2019-05-13  2019-05-13T10:53:54-04:00          86

    Day num
85        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
159  50638  Once a Day  2019-05-29  2019-05-29T09:40:46-04:00         160

     Day num
159        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
58  50639  Once a Day  2019-05-14  2019-05-14T11:00:04-04:00          59

    Day num
58        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
2  50661  Once a Day  2019-07-16  2019-07-16T11:04:30-04:00           3

   Day num
2        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
29  50662  Once a Day  2019-05-02  2019-05-02T18:22:00-04:00          30

    Day num
29        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
71  50666  Once a Day  2019-05-18  2019-05-18T05:59:53-04:00          72

    Day num
71        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
35  50671  Once a Day  2019-07-07  2019-07-07T18:32:46-04:00          36

    Day num
35        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
34  50675  Once a Day  2019-05-07  2019-05-07T20:39:19-04:00          35

    Day num
34        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
73  50682  Once a Day  2019-06-15  2019-06-15T13:48:43-04:00          74

    Day num
73        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
63  50683  Once a Day  2019-06-16  2019-06-16T21:02:39-04:00          64

    Day num
63        0
        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
138  50692  Once a Day  2019-06-13  2019-06-13T15:38:34-04:00         139

     Day num
138        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
75  50694  Once a Day  2019-07-01  2019-07-01T20:23:45-04:00          76

    Day num
75        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
61  50703  Once a Day  2019-06-14  2019-06-14T06:40:56-04:00          62

    Day num
61        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
74  50706  Once a Day  2019-07-03  2019-07-03T15:40:36-04:00          75

    Day num
74        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0  50720  Once a Day  2019-07-05  2019-07-05T16:35:36-04:00           1

   Day num
0        1
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
64  50722  Once a Day  2019-07-19  2019-07-19T19:05:00-04:00          65

    Day num
64        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
44  50723  Once a Day  2019-08-24  2019-08-24T19:05:02-04:00          45

    Day num
44        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
15  50728  Once a Day  2019-09-14  2019-09-14T09:15:48-04:00          16

    Day num
15        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
60  50732  Once a Day  2019-08-15  2019-08-15T18:15:12-04:00          61

    Day num
60        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
30  50735  Once a Day  2019-07-14  2019-07-14T13:26:17-04:00          31

    Day num
30        0
      ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
2  50741  Once a Day  2019-09-25  2019-09-25T11:56:26-04:00           3

   Day num
2        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
29  50742  Once a Day  2019-07-22  2019-07-22T08:32:38-04:00          30

    Day num
29        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
32  50745  Once a Day  2019-07-22  2019-07-22T07:48:24-04:00          33

    Day num
32        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
25  50767  Once a Day  2019-07-26  2019-07-26T08:16:51-04:00          26

    Day num
25        0

       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
85  50774  Once a Day  2019-10-06  2019-10-06T11:21:32-04:00          86

    Day num
85        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
32  50780  Once a Day  2019-09-03  2019-09-03T13:34:34-04:00          33

    Day num
32        0
       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
61  50788  Once a Day  2019-10-20  2019-10-20T17:57:33-04:00          62

    Day num
61        0

In [57]:
filenames = glob.glob('ID_*.csv')

filenames

['ID_50006.csv',
 'ID_50007.csv',
 'ID_50010.csv',
 'ID_50023.csv',
 'ID_50025.csv',
 'ID_50027.csv',
 'ID_50035.csv',
 'ID_50036.csv',
 'ID_50037.csv',
 'ID_50038.csv',
 'ID_50042.csv',
 'ID_50044.csv',
 'ID_50050.csv',
 'ID_50052.csv',
 'ID_50054.csv',
 'ID_50058.csv',
 'ID_50064.csv',
 'ID_50067.csv',
 'ID_50068.csv',
 'ID_50070.csv',
 'ID_50075.csv',
 'ID_50077.csv',
 'ID_50078.csv',
 'ID_50080.csv',
 'ID_50090.csv',
 'ID_50091.csv',
 'ID_50098.csv',
 'ID_50101.csv',
 'ID_50103.csv',
 'ID_50104.csv',
 'ID_50105.csv',
 'ID_50115.csv',
 'ID_50116.csv',
 'ID_50117.csv',
 'ID_50118.csv',
 'ID_50121.csv',
 'ID_50132.csv',
 'ID_50136.csv',
 'ID_50137.csv',
 'ID_50146.csv',
 'ID_50148.csv',
 'ID_50150.csv',
 'ID_50152.csv',
 'ID_50157.csv',
 'ID_50158.csv',
 'ID_50161.csv',
 'ID_50162.csv',
 'ID_50164.csv',
 'ID_50166.csv',
 'ID_50167.csv',
 'ID_50183.csv',
 'ID_50185.csv',
 'ID_50188.csv',
 'ID_50197.csv',
 'ID_50201.csv',
 'ID_50208.csv',
 'ID_50217.csv',
 'ID_50220.csv',
 'ID_50225.csv',
 'ID_50226.csv',
 'ID_50230.csv',
 'ID_50231.csv',
 'ID_50232.csv',
 'ID_50238.csv',
 'ID_50241.csv',
 'ID_50246.csv',
 'ID_50251.csv',
 'ID_50258.csv',
 'ID_50260.csv',
 'ID_50261.csv',
 'ID_50267.csv',
 'ID_50269.csv',
 'ID_50270.csv',
 'ID_50271.csv',
 'ID_50272.csv',
 'ID_50274.csv',
 'ID_50280.csv',
 'ID_50284.csv',
 'ID_50286.csv',
 'ID_50290.csv',
 'ID_50299.csv',
 'ID_50301.csv',
 'ID_50303.csv',
 'ID_50304.csv',
 'ID_50307.csv',
 'ID_50314.csv',
 'ID_50316.csv',
 'ID_50326.csv',
 'ID_50327.csv',
 'ID_50329.csv',
 'ID_50334.csv',
 'ID_50338.csv',
 'ID_50340.csv',
 'ID_50342.csv',
 'ID_50345.csv',
 'ID_50348.csv',
 'ID_50351.csv',
 'ID_50357.csv',
 'ID_50359.csv',
 'ID_50360.csv',
 'ID_50369.csv',
 'ID_50375.csv',
 'ID_50379.csv',
 'ID_50382.csv',
 'ID_50383.csv',
 'ID_50388.csv',
 'ID_50396.csv',
 'ID_50404.csv',
 'ID_50405.csv',
 'ID_50408.csv',
 'ID_50415.csv',
 'ID_50427.csv',
 'ID_50438.csv',
 'ID_50440.csv',
 'ID_50459.csv',
 'ID_50471.csv',
 'ID_50483.csv',
 'ID_50484.csv',
 'ID_50487.csv',
 'ID_50489.csv',
 'ID_50490.csv',
 'ID_50491.csv',
 'ID_50494.csv',
 'ID_50497.csv',
 'ID_50500.csv',
 'ID_50512.csv',
 'ID_50519.csv',
 'ID_50522.csv',
 'ID_50528.csv',
 'ID_50531.csv',
 'ID_50535.csv',
 'ID_50540.csv',
 'ID_50545.csv',
 'ID_50549.csv',
 'ID_50555.csv',
 'ID_50561.csv',
 'ID_50569.csv',
 'ID_50571.csv',
 'ID_50602.csv',
 'ID_50604.csv',
 'ID_50614.csv',
 'ID_50625.csv',
 'ID_50628.csv',
 'ID_50633.csv',
 'ID_50634.csv',
 'ID_50638.csv',
 'ID_50639.csv',
 'ID_50661.csv',
 'ID_50662.csv',
 'ID_50666.csv',
 'ID_50671.csv',
 'ID_50675.csv',
 'ID_50682.csv',
 'ID_50683.csv',
 'ID_50692.csv',
 'ID_50694.csv',
 'ID_50703.csv',
 'ID_50706.csv',
 'ID_50720.csv',
 'ID_50722.csv',
 'ID_50723.csv',
 'ID_50728.csv',
 'ID_50732.csv',
 'ID_50735.csv',
 'ID_50741.csv',
 'ID_50742.csv',
 'ID_50745.csv',
 'ID_50767.csv',
 'ID_50774.csv',
 'ID_50780.csv',
 'ID_50788.csv']

In [58]:
df_list = []

In [59]:
for f in filenames:
    df_list.append(pd.read_csv(f))

print(df_list)

[       ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0   50006           1  2016-11-12  2016-11-12T10:39:16-05:00           1
1   50006           1  2016-11-18  2016-11-18T11:57:08-05:00           2
2   50006           1  2016-11-19  2016-11-19T10:02:07-05:00           3
3   50006           1  2016-11-20  2016-11-20T08:27:06-05:00           4
4   50006           1  2016-11-21  2016-11-21T08:20:04-05:00           5
..    ...         ...         ...                        ...         ...
90  50006           1  2017-02-16  2017-02-16T07:54:11-05:00          91
91  50006           1  2017-02-17  2017-02-17T07:52:10-05:00          92
92  50006           1  2017-02-18  2017-02-18T08:27:08-05:00          93
93  50006           1  2017-02-19  2017-02-19T08:10:07-05:00          94
94  50006           1  2017-02-19  2017-02-19T11:55:07-05:00          95

    Day num
0         1
1         0
2         0
3         0
4         0
..      ...
90        0
91        0
92        0
93        0
94        0

[95 rows x 6 columns],        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0   50007           1  2016-11-17  2016-11-17T15:45:39-05:00           1
1   50007           1  2016-11-18  2016-11-18T08:01:38-05:00           2
2   50007           1  2016-11-19  2016-11-19T08:39:35-05:00           3
3   50007           1  2016-11-20  2016-11-20T09:07:32-05:00           4
4   50007           1  2016-11-21  2016-11-21T08:45:30-05:00           5
..    ...         ...         ...                        ...         ...
90  50007           1  2017-02-15  2017-02-15T06:23:47-05:00          91
91  50007           1  2017-02-16  2017-02-16T05:35:45-05:00          92
92  50007           1  2017-02-17  2017-02-17T10:14:42-05:00          93
93  50007           1  2017-02-18  2017-02-18T09:40:39-05:00          94
94  50007           1  2017-02-19  2017-02-19T09:28:37-05:00          95

    Day num
0         1
1         0
2         0
3         0
4         0
..      ...
90        0
91        0
92        0
93        0
94        0

[95 rows x 6 columns],        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0   50010           1  2016-11-25  2016-11-25T11:46:52-05:00           1
1   50010           1  2016-12-04  2016-12-04T16:17:28-05:00           2
2   50010           1  2016-12-05  2016-12-05T09:36:26-05:00           3
3   50010           1  2016-12-06  2016-12-06T09:00:23-05:00           4
4   50010           1  2016-12-07  2016-12-07T08:23:21-05:00           5
5   50010           1  2016-12-08  2016-12-08T08:46:18-05:00           6
6   50010           1  2016-12-09  2016-12-09T09:52:16-05:00           7
7   50010           1  2016-12-10  2016-12-10T09:14:13-05:00           8
8   50010           1  2016-12-11  2016-12-11T09:51:10-05:00           9
9   50010           1  2016-12-12  2016-12-12T09:52:08-05:00          10
10  50010           1  2016-12-13  2016-12-13T08:49:05-05:00          11
11  50010           1  2016-12-14  2016-12-14T11:02:02-05:00          12
12  50010           1  2016-12-15  2016-12-15T10:27:00-05:00          13
13  50010           1  2016-12-16  2016-12-16T07:24:58-05:00          14
14  50010           1  2016-12-17  2016-12-17T10:40:55-05:00          15
15  50010           1  2016-12-18  2016-12-18T09:39:52-05:00          16
16  50010           1  2016-12-19  2016-12-19T08:51:50-05:00          17
17  50010           1  2016-12-20  2016-12-20T09:47:47-05:00          18
18  50010           1  2016-12-22  2016-12-22T09:35:42-05:00          19
19  50010           1  2016-12-23  2016-12-23T12:16:39-05:00          20
20  50010           1  2016-12-24  2016-12-24T09:10:37-05:00          21
21  50010           1  2016-12-25  2016-12-25T08:50:34-05:00          22
22  50010           1  2016-12-27  2016-12-27T07:22:29-05:00          23
23  50010           1  2016-12-28  2016-12-28T10:52:26-05:00          24
24  50010           1  2016-12-29  2016-12-29T10:12:24-05:00          25
25  50010           1  2016-12-30  2016-12-30T09:05:21-05:00          26
26  50010           1  2017-01-01  2017-01-01T09:07:16-05:00          27
27  50010           1  2017-01-02  2017-01-02T10:35:13-05:00          28
28  50010           1  2017-01-03  2017-01-03T07:57:11-05:00          29
29  50010           1  2017-02-23  2017-02-23T10:42:59-05:00          30
30  50010           1  2017-02-25  2017-02-25T09:10:54-05:00          31
31  50010           1  2017-02-27  2017-02-27T09:38:48-05:00          32

    Day num
0         1
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
30        0
31        0  ,        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0   50023           1  2016-12-05  2016-12-05T23:28:23-05:00           1
1   50023           1  2016-12-06  2016-12-06T10:41:22-05:00           2
2   50023           1  2016-12-07  2016-12-07T16:47:20-05:00           3
3   50023           1  2016-12-08  2016-12-08T08:58:19-05:00           4
4   50023           1  2016-12-09  2016-12-09T22:16:16-05:00           5
5   50023           1  2016-12-10  2016-12-10T21:37:15-05:00           6
6   50023           1  2016-12-13  2016-12-13T09:42:11-05:00           7
7   50023           1  2016-12-13  2016-12-13T12:41:10-05:00           8
8   50023           1  2016-12-14  2016-12-14T09:31:09-05:00           9
9   50023           1  2016-12-15  2016-12-15T11:40:07-05:00          10
10  50023           1  2016-12-16  2016-12-16T00:05:06-05:00          11
11  50023           1  2016-12-19  2016-12-19T07:26:01-05:00          12
12  50023           1  2016-12-20  2016-12-20T22:34:58-05:00          13
13  50023           1  2016-12-23  2016-12-23T18:39:54-05:00          14
14  50023           1  2016-12-25  2016-12-25T21:29:50-05:00          15
15  50023           1  2016-12-25  2016-12-25T21:40:50-05:00          16
16  50023           1  2016-12-28  2016-12-28T23:19:45-05:00          17
17  50023           1  2017-02-20  2017-02-20T14:48:17-05:00          18

    Day num
0         1
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0  ,        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0   50025           1  2016-12-06  2016-12-06T12:15:36-05:00           1
1   50025           1  2016-12-06  2016-12-06T13:18:36-05:00           2
2   50025           1  2016-12-07  2016-12-07T13:27:35-05:00           3
3   50025           1  2016-12-08  2016-12-08T16:44:34-05:00           4
4   50025           1  2016-12-09  2016-12-09T14:54:34-05:00           5
5   50025           1  2016-12-10  2016-12-10T13:11:33-05:00           6
6   50025           1  2016-12-11  2016-12-11T13:12:32-05:00           7
7   50025           1  2016-12-12  2016-12-12T09:54:32-05:00           8
8   50025           1  2016-12-13  2016-12-13T07:54:31-05:00           9
9   50025           1  2016-12-14  2016-12-14T07:51:31-05:00          10
10  50025           1  2016-12-15  2016-12-15T07:19:30-05:00          11
11  50025           1  2016-12-16  2016-12-16T09:35:29-05:00          12
12  50025           1  2016-12-17  2016-12-17T13:04:28-05:00          13
13  50025           1  2016-12-18  2016-12-18T14:10:28-05:00          14
14  50025           1  2016-12-19  2016-12-19T14:22:27-05:00          15
15  50025           1  2016-12-20  2016-12-20T08:44:27-05:00          16
16  50025           1  2016-12-21  2016-12-21T09:54:26-05:00          17
17  50025           1  2016-12-22  2016-12-22T09:33:25-05:00          18
18  50025           1  2016-12-23  2016-12-23T10:47:24-05:00          19
19  50025           1  2016-12-24  2016-12-24T11:15:24-05:00          20
20  50025           1  2016-12-25  2016-12-25T14:00:23-05:00          21
21  50025           1  2016-12-26  2016-12-26T13:08:22-05:00          22
22  50025           1  2016-12-27  2016-12-27T08:23:22-05:00          23
23  50025           1  2017-01-31  2017-01-31T18:27:58-05:00          24
24  50025           1  2017-02-01  2017-02-01T14:14:57-05:00          25
25  50025           1  2017-02-02  2017-02-02T14:58:57-05:00          26
26  50025           1  2017-02-03  2017-02-03T10:57:56-05:00          27
27  50025           1  2017-02-04  2017-02-04T10:51:56-05:00          28
28  50025           1  2017-02-05  2017-02-05T10:53:55-05:00          29
29  50025           1  2017-02-06  2017-02-06T14:22:54-05:00          30
30  50025           1  2017-02-07  2017-02-07T12:11:54-05:00          31
31  50025           1  2017-02-08  2017-02-08T16:31:53-05:00          32
32  50025           1  2017-02-09  2017-02-09T15:37:52-05:00          33
33  50025           1  2017-02-10  2017-02-10T16:49:51-05:00          34
34  50025           1  2017-02-11  2017-02-11T13:58:51-05:00          35
35  50025           1  2017-02-12  2017-02-12T15:32:50-05:00          36
36  50025           1  2017-02-13  2017-02-13T09:59:50-05:00          37
37  50025           1  2017-02-14  2017-02-14T10:04:49-05:00          38
38  50025           1  2017-02-15  2017-02-15T10:22:48-05:00          39
39  50025           1  2017-02-16  2017-02-16T16:39:47-05:00          40
40  50025           1  2017-02-17  2017-02-17T08:45:47-05:00          41
41  50025           1  2017-02-18  2017-02-18T16:41:46-05:00          42
42  50025           1  2017-02-19  2017-02-19T19:25:45-05:00          43
43  50025           1  2017-02-20  2017-02-20T09:07:45-05:00          44
44  50025           1  2017-02-21  2017-02-21T09:29:44-05:00          45
45  50025           1  2017-02-22  2017-02-22T09:16:44-05:00          46
46  50025           1  2017-02-23  2017-02-23T11:26:43-05:00          47
47  50025           1  2017-04-12  2017-04-12T12:49:11-04:00          48

    Day num
0         1
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
30        0
31        0
32        0
33        0
34        0
35        0
36        0
37        0
38        0
39        0
40        0
41        0
42        0
43        0
44        0
45        0
46        0
47        0  ,        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0   50027           1  2016-12-24  2016-12-24T14:59:04-05:00           1
1   50027           1  2016-12-26  2016-12-26T10:03:07-05:00           2
2   50027           1  2016-12-27  2016-12-27T09:40:09-05:00           3
3   50027           1  2016-12-28  2016-12-28T07:57:10-05:00           4
4   50027           1  2016-12-30  2016-12-30T10:22:13-05:00           5
5   50027           1  2016-12-31  2016-12-31T08:08:15-05:00           6
6   50027           1  2017-01-01  2017-01-01T06:16:16-05:00           7
7   50027           1  2017-01-02  2017-01-02T10:15:18-05:00           8
8   50027           1  2017-01-03  2017-01-03T06:06:19-05:00           9
9   50027           1  2017-01-04  2017-01-04T07:43:21-05:00          10
10  50027           1  2017-01-05  2017-01-05T06:50:22-05:00          11
11  50027           1  2017-01-06  2017-01-06T07:57:24-05:00          12
12  50027           1  2017-01-07  2017-01-07T06:35:25-05:00          13
13  50027           1  2017-01-08  2017-01-08T08:08:27-05:00          14
14  50027           1  2017-01-09  2017-01-09T07:36:28-05:00          15
15  50027           1  2017-01-10  2017-01-10T08:48:30-05:00          16
16  50027           1  2017-01-11  2017-01-11T08:22:31-05:00          17
17  50027           1  2017-01-13  2017-01-13T09:31:34-05:00          18
18  50027           1  2017-01-14  2017-01-14T10:25:36-05:00          19
19  50027           1  2017-01-15  2017-01-15T10:29:37-05:00          20
20  50027           1  2017-01-16  2017-01-16T06:35:39-05:00          21
21  50027           1  2017-01-17  2017-01-17T08:29:40-05:00          22
22  50027           1  2017-01-18  2017-01-18T09:19:42-05:00          23
23  50027           1  2017-01-19  2017-01-19T08:56:43-05:00          24
24  50027           1  2017-01-20  2017-01-20T08:51:45-05:00          25
25  50027           1  2017-01-21  2017-01-21T07:48:46-05:00          26
26  50027           1  2017-01-22  2017-01-22T08:05:48-05:00          27
27  50027           1  2017-01-23  2017-01-23T08:01:49-05:00          28
28  50027           1  2017-01-24  2017-01-24T08:48:51-05:00          29
29  50027           1  2017-01-25  2017-01-25T09:37:53-05:00          30
30  50027           1  2017-01-26  2017-01-26T12:40:54-05:00          31
31  50027           1  2017-01-27  2017-01-27T10:29:56-05:00          32
32  50027           1  2017-01-28  2017-01-28T08:21:57-05:00          33
33  50027           1  2017-01-29  2017-01-29T08:27:59-05:00          34
34  50027           1  2017-01-30  2017-01-30T08:55:00-05:00          35
35  50027           1  2017-01-31  2017-01-31T09:28:02-05:00          36
36  50027           1  2017-02-01  2017-02-01T09:34:03-05:00          37
37  50027           1  2017-02-02  2017-02-02T09:29:05-05:00          38
38  50027           1  2017-02-03  2017-02-03T07:07:06-05:00          39
39  50027           1  2017-02-04  2017-02-04T08:18:08-05:00          40
40  50027           1  2017-02-06  2017-02-06T08:48:11-05:00          41
41  50027           1  2017-02-07  2017-02-07T08:53:12-05:00          42
42  50027           1  2017-02-08  2017-02-08T08:41:14-05:00          43
43  50027           1  2017-02-09  2017-02-09T13:23:16-05:00          44
44  50027           1  2017-02-10  2017-02-10T12:50:17-05:00          45
45  50027           1  2017-02-11  2017-02-11T07:59:18-05:00          46
46  50027           1  2017-02-12  2017-02-12T08:38:20-05:00          47
47  50027           1  2017-02-14  2017-02-14T06:54:23-05:00          48

    Day num
0         1
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
30        0
31        0
32        0
33        0
34        0
35        0
36        0
37        0
38        0
39        0
40        0
41        0
42        0
43        0
44        0
45        0
46        0
47        0  ,        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0   50035           1  2016-12-05  2016-12-05T18:31:33-05:00           1
1   50035           1  2016-12-10  2016-12-10T22:53:27-05:00           2
2   50035           1  2016-12-11  2016-12-11T13:38:27-05:00           3
3   50035           1  2016-12-17  2016-12-17T12:50:20-05:00           4
4   50035           1  2016-12-17  2016-12-17T19:46:19-05:00           5
5   50035           1  2016-12-23  2016-12-23T22:35:12-05:00           6
6   50035           1  2016-12-23  2016-12-23T22:59:12-05:00           7
7   50035           1  2016-12-26  2016-12-26T14:09:09-05:00           8
8   50035           1  2016-12-26  2016-12-26T21:41:09-05:00           9
9   50035           1  2016-12-27  2016-12-27T08:16:08-05:00          10
10  50035           1  2016-12-27  2016-12-27T08:57:08-05:00          11
11  50035           1  2017-01-08  2017-01-08T11:09:54-05:00          12
12  50035           1  2017-01-08  2017-01-08T22:03:54-05:00          13
13  50035           1  2017-01-09  2017-01-09T22:11:52-05:00          14
14  50035           1  2017-01-12  2017-01-12T22:48:49-05:00          15
15  50035           1  2017-01-18  2017-01-18T21:13:42-05:00          16
16  50035           1  2017-01-21  2017-01-21T18:12:39-05:00          17
17  50035           1  2017-01-24  2017-01-24T22:23:35-05:00          18
18  50035           1  2017-02-06  2017-02-06T21:50:20-05:00          19
19  50035           1  2017-02-07  2017-02-07T15:54:19-05:00          20
20  50035           1  2017-02-09  2017-02-09T11:19:17-05:00          21
21  50035           1  2017-02-12  2017-02-12T10:23:13-05:00          22
22  50035           1  2017-02-13  2017-02-13T07:39:12-05:00          23
23  50035           1  2017-02-14  2017-02-14T09:03:11-05:00          24
24  50035           1  2017-02-14  2017-02-14T21:52:10-05:00          25
25  50035           1  2017-02-26  2017-02-26T08:50:57-05:00          26
26  50035           1  2017-02-26  2017-02-26T09:06:57-05:00          27
27  50035           1  2017-03-27  2017-03-27T22:40:23-04:00          28
28  50035           1  2017-04-01  2017-04-01T17:04:17-04:00          29
29  50035           1  2017-04-08  2017-04-08T22:25:09-04:00          30
30  50035           1  2017-04-10  2017-04-10T11:49:07-04:00          31

    Day num
0         1
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0
16        0
17        0
18        0
19        0
20        0
21        0
22        0
23        0
24        0
25        0
26        0
27        0
28        0
29        0
30        0  ,        ID  Dose Label   Dose Date             Dose Timestamp  Dose Index  \
0   50036           1  2017-03-27  2017-03-27T15:14:59-04:00           1
1   50036           1  2017-03-29  2017-03-29T16:03:57-04:00           2
2   50036           1  2017-03-30  2017-03-30T10:48:56-04:00           3
3   50036           1  2017-03-31  2017-03-31T21:02:54-04:00           4
4   50036           1  2017-04-01  2017-04-01T12:25:53-04:00           5
5   50036           1  2017-04-01  2017-04-01T22:36:52-04:00           6
6   50036           1  2017-04-05  2017-04-05T18:56:47-04:00           7
7   50036           1  2017-04-06  2017-04-06T17:08:46-04:00           8
8   50036           1  2017-04-08  2017-04-08T00:04:44-04:00           9
9   50036           1  2017-04-12  2017-04-12T18:37:38-04:00          10
10  50036           1  2017-04-14  2017-04-14T20:01:35-04:00          11
11  50036           1  2017-04-16  2017-04-16T01:33:34-04:00          12
12  50036           1  2017-04-17  2017-04-17T12:00:32-04:00          13
13  50036           1  2017-04-18  2017-04-18T23:31:30-04:00          14
14  50036           1  2017-04-22  2017-04-22T10:42:25-04:00          15
15  50036           1  2017-05-01  2017-05-01T22:15:13-04:00          16
16  50036           1  2017-06-09  2017-06-09T09:12:22-04:00          17
17  50036           1  2017-06-15  2017-06-15T09:54:14-04:00          18
18  50036           1  2017-07-03  2017-07-03T22:49:49-04:00          19
19  50036           1  2017-08-15  2017-08-15T15:12:52-04:00          20
20  50036           1  2017-08-19  2017-08-19T15:50:47-04:00          21
21  50036           1  2017-08-20  2017-08-20T12:09:46-04:00          22
22  50036           1  2017-08-21  2017-08-21T19:58:44-04:00          23
23  50036           1  2017-08-24  2017-08-24T22:50:40-04:00          24
24  50036           1  2017-08-28  2017-08-28T22:36:35-04:00          25
25  50036           1  2017-08-29  2017-08-29T10:15:34-04:00          26
26  50036           1  2017-09-12  2017-09-12T21:49:15-04:00          27
27  50036           1  2017-09-26  2017-09-26T18:54:56-04:00          28
28  50036           1  2018-03-10  2018-03-10T12:52:18-05:00          29

    Day num
0         1
1         0
2         0
3         0
4         0
5         0
6         0
7         0
8         0
9         0
10        0
11        0
12        0
13        0
14        0
15        0

In [60]:
df_all = pd.concat([d.iloc[-1:] for d in df_list], ignore_index=True)

df_all

,ID,Dose Label,Dose Date,Dose Timestamp,Dose Index,Day num
0,50006,1,2017-02-19,2017-02-19T11:55:07-05:00,95,0
1,50007,1,2017-02-19,2017-02-19T09:28:37-05:00,95,0
2,50010,1,2017-02-27,2017-02-27T09:38:48-05:00,32,0
3,50023,1,2017-02-20,2017-02-20T14:48:17-05:00,18,0
4,50025,1,2017-04-12,2017-04-12T12:49:11-04:00,48,0
...,...,...,...,...,...,...
166,50745,Once a Day,2019-07-22,2019-07-22T07:48:24-04:00,33,0
167,50767,Once a Day,2019-07-26,2019-07-26T08:16:51-04:00,26,0
168,50774,Once a Day,2019-10-06,2019-10-06T11:21:32-04:00,86,0
169,50780,Once a Day,2019-09-03,2019-09-03T13:34:34-04:00,33,0
170,50788,Once a Day,2019-10-20,2019-10-20T17:57:33-04:00,62,0

In [61]:
#Merge with day2 dataset
Start_end_dates = day2.merge(df_all, on='ID', how='left')

Start_end_dates

,ID,Day num_x,Dose Label_x,Dose Date_x,Last Date_50,ID_str,Dose Label_y,Dose Date_y,Dose Timestamp,Dose Index,Day num_y
0,50334,1,Twice a Day,2018-01-14,2018-03-05,50334,Twice a Day,2018-04-07,2018-04-07T21:59:47-04:00,122,0
1,50404,1,Twice a Day,2018-06-21,2018-08-10,50404,Twice a Day,2018-09-12,2018-09-12T23:43:39-04:00,166,0
2,50303,1,Once a Day,2018-02-12,2018-04-03,50303,Once a Day,2018-03-15,2018-03-15T08:54:16-04:00,31,0
3,50329,1,Once a Day,2018-01-13,2018-03-04,50329,Once a Day,2018-01-13,2018-01-13T00:23:31-05:00,1,1
4,50338,1,Once a Day,2018-02-07,2018-03-29,50338,Once a Day,2018-04-23,2018-04-23T21:40:43-04:00,21,0
...,...,...,...,...,...,...,...,...,...,...,...
166,50307,1,1,2017-12-05,2018-01-24,50307,1,2018-01-28,2018-01-28T14:47:09-05:00,26,0
167,50314,1,1,2017-12-08,2018-01-27,50314,1,2018-04-19,2018-04-19T15:52:40-04:00,106,0
168,50316,1,1,2017-12-07,2018-01-26,50316,1,2018-03-13,2018-03-13T12:58:37-04:00,88,0
169,50326,1,1,2018-01-11,2018-03-02,50326,1,2018-04-23,2018-04-23T14:05:58-04:00,83,0
170,50327,1,1,2018-01-04,2018-02-23,50327,1,2018-07-14,2018-07-14T14:34:40-04:00,39,0

In [62]:
pd.DataFrame(Start_end_dates).to_excel('Start_end_dates.xlsx', index=False)
print('DataFrame is written to Excel File successfully.')

DataFrame is written to Excel File successfully.